In [1]:
import numpy as np

In [2]:
a=np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
a

array([[200, 220, 250],
       [ 68,  79, 105],
       [110, 140, 180],
       [ 80,  85,  90]])

In [3]:
75*a

array([[15000, 16500, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

In [4]:
units_sold=np.array([[50,60,25],[10,13,5],[40,70,52]])
price_per_unit=np.array([20,30,15])

In [5]:
units_sold

array([[50, 60, 25],
       [10, 13,  5],
       [40, 70, 52]])

In [6]:
price_per_unit

array([20, 30, 15])

In [7]:
np.dot(price_per_unit,units_sold)

array([1900, 2640, 1430])